
version: '2'

services:

  red_tetris:
    image: "mgreil/red_tetris"
    restart: always
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - "web_network"
    build: ./
    volumes:
      - ./src:/opt/red_tetris/src

networks:
  web_network:
    driver: bridge
